In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1={
    "name":["rohan","seema","mahesh","shruti"],
    "marks":[9,55,67,98],
    "city":["Delhi","Jaipur","Rampur","Barilly"]
}

In [3]:
df=pd.DataFrame(dict1)

In [4]:
df

     name  marks     city
0   rohan      9    Delhi
1   seema     55   Jaipur
2  mahesh     67   Rampur
3  shruti     98  Barilly

In [5]:
df.index=[1,2,3,4]

In [6]:
df

     name  marks     city
1   rohan      9    Delhi
2   seema     55   Jaipur
3  mahesh     67   Rampur
4  shruti     98  Barilly

In [7]:
ser=pd.Series(np.random.rand(20))

In [8]:
ser

0     0.899968
1     0.078334
2     0.182431
3     0.844022
4     0.154632
5     0.259079
6     0.728102
7     0.917181
8     0.592957
9     0.859270
10    0.933097
11    0.584238
12    0.780830
13    0.507256
14    0.229036
15    0.256936
16    0.844247
17    0.550219
18    0.545124
19    0.025179
dtype: float64

In [9]:
type(ser)

pandas.Series

In [10]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))

In [11]:
newdf

            0         1         2         3         4
0    0.031684  0.112795  0.854318  0.148441  0.587281
1    0.093068  0.432875  0.182104  0.450309  0.060322
2    0.562060  0.120284  0.476956  0.726568  0.926136
3    0.627921  0.351236  0.779381  0.494359  0.834957
4    0.639259  0.204240  0.077666  0.418233  0.082384
..        ...       ...       ...       ...       ...
329  0.863107  0.208363  0.524254  0.530996  0.801479
330  0.754327  0.059137  0.689098  0.070480  0.939076
331  0.679795  0.835429  0.655131  0.215100  0.341268
332  0.946301  0.960159  0.515938  0.825161  0.304711
333  0.909683  0.456038  0.132587  0.819226  0.786179

[334 rows x 5 columns]

In [12]:
newdf.head(3)

          0         1         2         3         4
0  0.031684  0.112795  0.854318  0.148441  0.587281
1  0.093068  0.432875  0.182104  0.450309  0.060322
2  0.562060  0.120284  0.476956  0.726568  0.926136

In [13]:
newdf.tail(3)

            0         1         2         3         4
331  0.679795  0.835429  0.655131  0.215100  0.341268
332  0.946301  0.960159  0.515938  0.825161  0.304711
333  0.909683  0.456038  0.132587  0.819226  0.786179

In [14]:
newdf.sort_index(axis=0)

            0         1         2         3         4
0    0.031684  0.112795  0.854318  0.148441  0.587281
1    0.093068  0.432875  0.182104  0.450309  0.060322
2    0.562060  0.120284  0.476956  0.726568  0.926136
3    0.627921  0.351236  0.779381  0.494359  0.834957
4    0.639259  0.204240  0.077666  0.418233  0.082384
..        ...       ...       ...       ...       ...
329  0.863107  0.208363  0.524254  0.530996  0.801479
330  0.754327  0.059137  0.689098  0.070480  0.939076
331  0.679795  0.835429  0.655131  0.215100  0.341268
332  0.946301  0.960159  0.515938  0.825161  0.304711
333  0.909683  0.456038  0.132587  0.819226  0.786179

[334 rows x 5 columns]

In [15]:
newdf.head(3)

          0         1         2         3         4
0  0.031684  0.112795  0.854318  0.148441  0.587281
1  0.093068  0.432875  0.182104  0.450309  0.060322
2  0.562060  0.120284  0.476956  0.726568  0.926136

In [16]:
newdf.tail(3)

            0         1         2         3         4
331  0.679795  0.835429  0.655131  0.215100  0.341268
332  0.946301  0.960159  0.515938  0.825161  0.304711
333  0.909683  0.456038  0.132587  0.819226  0.786179

In [17]:
newdf.sort_index(axis=0)

            0         1         2         3         4
0    0.031684  0.112795  0.854318  0.148441  0.587281
1    0.093068  0.432875  0.182104  0.450309  0.060322
2    0.562060  0.120284  0.476956  0.726568  0.926136
3    0.627921  0.351236  0.779381  0.494359  0.834957
4    0.639259  0.204240  0.077666  0.418233  0.082384
..        ...       ...       ...       ...       ...
329  0.863107  0.208363  0.524254  0.530996  0.801479
330  0.754327  0.059137  0.689098  0.070480  0.939076
331  0.679795  0.835429  0.655131  0.215100  0.341268
332  0.946301  0.960159  0.515938  0.825161  0.304711
333  0.909683  0.456038  0.132587  0.819226  0.786179

[334 rows x 5 columns]

In [18]:
newdf.drop(0,axis=1)

            1         2         3         4
0    0.112795  0.854318  0.148441  0.587281
1    0.432875  0.182104  0.450309  0.060322
2    0.120284  0.476956  0.726568  0.926136
3    0.351236  0.779381  0.494359  0.834957
4    0.204240  0.077666  0.418233  0.082384
..        ...       ...       ...       ...
329  0.208363  0.524254  0.530996  0.801479
330  0.059137  0.689098  0.070480  0.939076
331  0.835429  0.655131  0.215100  0.341268
332  0.960159  0.515938  0.825161  0.304711
333  0.456038  0.132587  0.819226  0.786179

[334 rows x 4 columns]

In [ ]:
newdf.dropna(inplace=True)